package com.enil.logez.feature.settings

import androidx.activity.compose.BackHandler
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.WindowInsets
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.outlined.ArrowBack
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.ListItem
import androidx.compose.material3.ListItemDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.produceState
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontFamily
import com.enil.logez.R
import com.enil.logez.core.designsystem.ScreenTitle
import com.enil.logez.core.designsystem.Spacing
import com.enil.logez.core.designsystem.logEzTopAppBarColors
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/** One entry of `assets/licenses/notices.json`: a library (or family) and the licence it ships under. */
@Serializable
data class OssNotice(
    val name: String,
    val artifacts: List<String> = emptyList(),
    val copyright: String = "",
    val license: String,
    /** A text file beside notices.json, or null for a licence that is only linked (Google Play services). */
    val file: String? = null,
    val url: String? = null,
)

internal object OssNotices {
    const val DIR = "licenses"
    const val INDEX = "$DIR/notices.json"
    private val json = Json { ignoreUnknownKeys = true }

    fun parse(text: String): List<OssNotice> = json.decodeFromString(text)
}

/**
 * Settings > About > Open-source licences (Play-readiness audit, 2026-09-25). The app bundles
 * MIT-licensed muscle geometry, three SIL OFL fonts, MapLibre's BSD notices and a long list of
 * Apache-2.0 libraries; most of those licences require their notice to travel with the app, and
 * none of it was viewable anywhere before this screen.
 *
 * Hand-maintained rather than generated by Google's oss-licenses plugin, whose compatibility with
 * this project's pinned AGP 9.2 is unverified. The index and texts live in `assets/licenses/`, and
 * LicensesAssetsTest fails if an entry points at a missing text. Update notices.json whenever a
 * dependency is added.
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun LicensesScreen(onBack: () -> Unit) {
    val context = LocalContext.current
    val notices by produceState(initialValue = emptyList<OssNotice>()) {
        value = withContext(Dispatchers.IO) {
            runCatching { OssNotices.parse(context.assets.open(OssNotices.INDEX).bufferedReader().use { it.readText() }) }
                .getOrDefault(emptyList())
        }
    }
    var openName by rememberSaveable { mutableStateOf<String?>(null) }
    val open = notices.firstOrNull { it.name == openName }

    if (open != null) {
        BackHandler { openName = null }
        LicenseTextScreen(notice = open, onBack = { openName = null })
        return
    }

    Scaffold(
        topBar = {
            TopAppBar(
                windowInsets = WindowInsets(0),
                colors = logEzTopAppBarColors(),
                title = { ScreenTitle(stringResource(R.string.licenses_title)) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Outlined.ArrowBack, contentDescription = stringResource(R.string.back))
                    }
                },
            )
        },
    ) { padding ->
        LazyColumn(modifier = Modifier.fillMaxSize().padding(padding)) {
            item(key = "intro") {
                Text(
                    stringResource(R.string.licenses_intro),
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    modifier = Modifier.padding(horizontal = Spacing.md, vertical = Spacing.sm),
                )
            }
            items(notices, key = { it.name }) { notice ->
                ListItem(
                    colors = ListItemDefaults.colors(containerColor = MaterialTheme.colorScheme.background),
                    headlineContent = { Text(notice.name) },
                    supportingContent = {
                        Text(
                            listOf(notice.license, notice.copyright).filter { it.isNotBlank() }.joinToString(" · "),
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                    },
                    modifier = if (notice.file != null || notice.url != null) {
                        Modifier.clickable { openName = notice.name }
                    } else {
                        Modifier
                    },
                )
            }
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun LicenseTextScreen(notice: OssNotice, onBack: () -> Unit) {
    val context = LocalContext.current
    val text by produceState(initialValue = "", notice.file) {
        value = withContext(Dispatchers.IO) {
            val file = notice.file ?: return@withContext notice.url.orEmpty()
            runCatching { context.assets.open("${OssNotices.DIR}/$file").bufferedReader().use { it.readText() } }.getOrDefault("")
        }
    }
    Scaffold(
        topBar = {
            TopAppBar(
                windowInsets = WindowInsets(0),
                colors = logEzTopAppBarColors(),
                title = { ScreenTitle(notice.name) },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Outlined.ArrowBack, contentDescription = stringResource(R.string.back))
                    }
                },
            )
        },
    ) { padding ->
        // Lazy, one paragraph per item: some notices are large (Google Play services' third-party
        // list is over 400 KB), and a single Text would lay the whole file out at once.
        val paragraphs = remember(text) { text.split(Regex("\\n\\s*\\n")).filter { it.isNotBlank() } }
        LazyColumn(
            modifier = Modifier.fillMaxSize().padding(padding),
            contentPadding = PaddingValues(Spacing.md),
        ) {
            if (notice.copyright.isNotBlank()) {
                item(key = "copyright") {
                    Text(notice.copyright, style = MaterialTheme.typography.bodyMedium, modifier = Modifier.padding(bottom = Spacing.sm))
                }
            }
            notice.url?.let { url ->
                item(key = "url") {
                    Text(url, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.primary, modifier = Modifier.padding(bottom = Spacing.md))
                }
            }
            items(paragraphs.size) { index ->
                Text(
                    paragraphs[index].trim(),
                    style = MaterialTheme.typography.bodySmall.copy(fontFamily = FontFamily.Monospace),
                    modifier = Modifier.padding(bottom = Spacing.sm),
                )
            }
        }
    }
}
